[package]
name = "asm-memo"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
mollusk-svm = "0.5.1"
mollusk-svm-bencher = "0.5.1"
solana-sdk = "2.2.1"

[features]
test-sbf = []

[lib]
crate-type = ["lib", "cdylib"]

